### ISSUE TITLE
boot device selection support

### ISSUE THREAD

**Issue by schnoddelbotz** [schnoddelbotz/amtc#4]
It has been on the usage screen for long, but I never found time to actually include it: `amtc -Ub pxe foobar.example.com` should power up that host, letting it boot off PXE - even if BIOS defaults to HDD. Current work-around here is to manage clients' `pxelinux.cfg` files.
As a follow-up, amtc-web's scheduler/GUI should support selecting the boot device.

**Comment by maratoid** [comment]
Hi! Any update on this?
Thanks. I'm trying to use this tool in combination with Openstack Ironic - since Ironic's AMT 9 driver is prone to hangups and timeouts.

**Comment by schnoddelbotz** [comment]
Hi,
thanks for your feedback and for showing interest in this feature.
Please give me one more week -- I just requested a test machine from colleagues and will take a look at the issue the next days coming. I'll report back in the next couple of days, promised.

**Comment by maratoid** [comment]
Thanks!

**Comment by maratoid** [comment]
Hi again! I've implemented an ugly hack in my fork to do what I need in the meantime. You might be able to re-use the wsman commands: https://github.com/maratoid/amtc

**Comment by schnoddelbotz** [comment]
Cool! As stated in the readme, amtc is a hack - so your hack perfectly matches project style ;)
Thank you for this contribution. I had no chance to test it yet, but do I understand correctly that you have to invoke amtc twice now to achieve proper boot device selection (i.e. -X or -H first, then -F to 'fixate' selected device)? If so, I think we could extend the section that starts with comment '(just another) hack for ws-man' ;). It already sends "2nd step" requests for INFO and ENUMERATE type requests. Guess it would be easy to send the -F(ixate) thing from there to avoid the need of second invocation...?
I'll take a closer look at this tomorrow and on how to merge...
Thanks again so far!!

**Comment by schnoddelbotz** [comment]
I pulled in your additions and tried to reduce it to a single invocation (removed -F command).
Seems to work fine on my Esprimo 910! Please let me know whether/how you'd like to be credited for this contribution. Should I create an authors.md file and add you ... or ...? Feel free to create a pull request; it would probably also ensure to get you on the repo's contributors list, which didn't happen automagically when I merged your changes -- sorry.
I'll finally close this issue after adding the command to the WebUI.
cheers!

**Comment by maratoid** [comment]
Awesome. No need for an attribution.

**Comment by schnoddelbotz** [comment]
Great. Again, thanks!
Closing the issue and scheduling a release for the new feature.

PS. Would somehow be interesting to hear whether amtc will really prove more reliable for your special use-case. AMT tends to be unreachable during boot for some seconds. If amtc should run into same problems as your current "driver", please give a shout -- might probably be worth to think about a --retries option/hack for amtc then...
