### ISSUE TITLE
Installer fails on El Capitan beta

### ISSUE THREAD

**Issue by endquote** [schnoddelbotz/amtc#7]
![screenshot 2015-08-21 09 35 28](https://cloud.githubusercontent.com/assets/330010/9413654/169e175e-47e8-11e5-869c-71904ff3d5e5.png)

![screenshot 2015-08-21 09 36 57](https://cloud.githubusercontent.com/assets/330010/9413676/360c93ea-47e8-11e5-979f-027fab3cc695.png)

**Comment by schnoddelbotz** [comment]
El Capitan's [SIP](https://en.wikipedia.org/wiki/System_Integrity_Protection) enforced a move of amtc from `/usr/bin` to `/usr/local/bin`.
I've added an [updated package](https://github.com/schnoddelbotz/amtc/releases/download/v0.8.5-alpha3/amtc_0.8.5.alpha4-OSX_10.11.pkg) for 10.11 to the [releases page](https://github.com/schnoddelbotz/amtc/releases).
Thanks for your feedback!

**Comment by endquote** [comment]
Seems to work!
