### ISSUE TITLE
amtc in EPEL

### ISSUE THREAD

**Issue by StykMartin** [schnoddelbotz/amtc#9]
It is nice to have RPMs here in GitHub. But I think it would be better if we can get RPMs from EPEL. 
https://fedoraproject.org/wiki/EPEL/FAQ

**Comment by StykMartin** [comment]
@schnoddelbotz what do you think about it?

**Comment by schnoddelbotz** [comment]
Sounds interesting. I surely don't have any objections and would also be willing to support such an effort (make required changes, ideally via PRs) -- but I have no resources to drive that topic.
Given it's also in FreeBSD ports for a while now -- would be cool to see it in EPEL, too :-)

Please just let me know how I can help with this.
Cheers!
